### ISSUE TITLE
Vertex Colors not being shown or loaded?

### ISSUE THREAD

**Issue by BeezBumba** [nbarkhina/N64Wasm#55]
I've been playing this rom hack of the Super Mario 64 game and in a certain level some textures just appear as white, but other emulators the texture is colored. This is not something only on this rom hack, it's also on another one. The first two are the same game(Return to Yoshi's Island DEMO 64) and the last 2 are a different game(That Time I Became Friends With The Royal Scuttlebug Family And Fell From Space, Yeah the long name is intentional). I think this has something to do with vertex colors because you can still see the grass texture, it's just white. The ones that do have color I used the ParaLLel RetroArch core.
![Screenshot 2024-06-13 174826](https://github.com/nbarkhina/N64Wasm/assets/172677510/8a9b6fd4-23bc-47d1-9327-52ee29770dc6)
![Screenshot 2024-06-13 175229](https://github.com/nbarkhina/N64Wasm/assets/172677510/406b58bf-f3b3-4a8f-bf90-90fb3c87ef00)
![Screenshot 2024-06-13 175713](https://github.com/nbarkhina/N64Wasm/assets/172677510/9d5077ea-dc87-482a-80a4-00a5b7543464)
![Screenshot 2024-06-13 180110](https://github.com/nbarkhina/N64Wasm/assets/172677510/f32879a1-d42c-4673-bfe9-c423f4447581)

**Comment by nbarkhina** [comment]
Not too sure about this one... you can try taking a look at the file Glide64_Ini.c

https://github.com/nbarkhina/N64Wasm/blob/master/code/src/glide2gl/src/Glide64/Glide64_Ini.c

 it has a bunch of game specific hacks. Perhaps it's not detecting the rom hack as super Mario 64, or you can play around with the different settings in that file.

**Comment by BeezBumba** [comment]
What was the need for all of these game specific settings?

**Comment by BeezBumba** [comment]
Although it might not be that because in software rendering mode (angrylion) I can see the color.

**Comment by nbarkhina** [comment]
I don't think software rendering uses those game specific settings, thats only when it does hardware acceleration. it's basically different settings that work better for certain games.

**Comment by BeezBumba** [comment]
I have a idea, that game was using a multitexture for the grass. maybe for some reason the color texture did not load in and only the detail texture. I know rendering 2 textures on a plane require 2 cycle mode, so does your emulator use 1 cycle or 2 cycle mode?

**Comment by BeezBumba** [comment]
I have a idea, the games was using a multitexture for the grass. maybe for some reason the color texture did not load in and only the detail texture loaded. I know using 2 textures require 2 cycle mode, so does your emulator use 1 cycle or 2 cycle mode?

**Comment by nbarkhina** [comment]
I'm really not sure but if parallel on retroarch works this is basically the same emulator. It's possible something is different on web since that uses OpenGL ES vs OpenGL proper on Desktop.

**Comment by BeezBumba** [comment]
I mean does the angrylion mode still use OpenGL?

**Comment by nbarkhina** [comment]
Angrylion does not use OpenGL. It's fully software based renderer which is why it's accurate at the cost of speed.

**Comment by BeezBumba** [comment]
What version of OpenGL ES is it using?

**Comment by BeezBumba** [comment]
nevermind why cant you just use opengl instead of opengl ES on browser?

**Comment by nbarkhina** [comment]
Browsers only support OpenGL ES

**Comment by BeezBumba** [comment]
It might just be a problem with OpenGL ES, because I know that every triangle has a shader on it that finds the right pixel colors. Those shaders just don't work for some reason on the emulator or I guess OpenGL ES.

**Comment by nbarkhina** [comment]
It uses OpenGL ES 3.00

**Comment by BeezBumba** [comment]
Is it possible to use openGL ES 3.2?

**Comment by BeezBumba** [comment]
Is it possible to use openGL ES 3.2?

**Comment by nbarkhina** [comment]
in mymain.cpp search for the line

    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);

you can try playing around with that by adding another line 

    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);

and see if the browser will use that or not

**Comment by BeezBumba** [comment]
Gave me these errors when trying 3.1 and 3.2 ```
n64wasm.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getParameter')
    at _glGetString (n64wasm.js:1:214421)
    at n64wasm.wasm:0xf17a0
    at Module._main (n64wasm.js:1:245516)
    at Object.callMain (n64wasm.js:1:250491)
    at MyClass.LoadEmulator (script.js:225:20)
```

**Comment by BeezBumba** [comment]
Appears that ANGLE has not made support for openGL ES 3.2 yet and we just have to wait.

**Comment by BeezBumba** [comment]
Is it possible to use WebGPU?

**Comment by BeezBumba** [comment]
https://developer.chrome.com/blog/from-webgl-to-webgpu/
